name: Evaluate

on:
  workflow_dispatch:
    inputs:
      datasets:
        description: 'Datasets to evaluate against'
        required: true
        default: 'base_evals/medium_example.yaml,base_evals/hard_example.yaml'
      compare_branch:
        description: 'Branch to compare against (leave empty for single evaluation)'
        required: false
        default: ''
      evaluators:
        description: 'Evaluators to run'
        required: true
        default: 'base_evaluator,ui_evaluator'
      num_repetitions:
        description: 'Number of repetitions for each evaluation'
        required: true
        default: 3
      pr_number:
        description: 'Pull Request number to comment on (optional)'
        required: false
      post_on_slack:
        description: 'Post results to Slack'
        required: false
        default: true
        type: boolean
      test_type:
        description: 'Type of test to run'
        type: choice
        required: true
        default: 'end_to_end'
        options:
          - end_to_end
          - memories

jobs:
  post-results:
    name: Post Evaluation Results to PR
    environment: staging
    if: always() && github.event.inputs.pr_number != ''
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Comment on PR (if PR number provided)
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = parseInt(`${{ github.event.inputs.pr_number }}`);

            if (!prNumber) {
              console.log('No PR number provided. Skipping comment.');
              return;
            }

            console.log(`Commenting on PR #${prNumber}...`);

            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "it worked"
            });
