name: Trigger Workflows when Commenting on a PR

on:
  issue_comment:
    types: [created]

permissions:
  pull-requests: write
  contents: read
  actions: write
  issues: write  # needed for posting comments and editing comments

jobs:
  trigger-evaluate:
    if: |
      github.event_name == 'issue_comment' &&
      github.event.issue.pull_request &&
      startsWith(github.event.comment.body, '/evaluate')
    runs-on: ubuntu-latest

    steps:
      - name: Handle /evaluate comment
        uses: masenf/comment-trigger-feedback@main
        with:
          script: |
            const body = context.payload.comment.body.trim();
            const parts = body.split(/\s+/);
            let testType = 'end_to_end';
            if (parts.length > 1) {
              testType = parts[1];
            }

            const prNumber = context.issue.number;
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber
            });

            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'evaluate.yaml',
              ref: 'main',
              inputs: {
                compare_branch: pr.data.head.ref,
                pr_number: String(prNumber),
                test_type: testType
              }
            });
          # These are the defaults, shown for clarity
          loading_reaction: "eyes"
          success_reaction: "+1"
          failure_reaction: "confused"
